# Setting Language
language: ja

#Setting Level UP exp
need-exp-levelup: 100

#SETTING LEVEL UP
need-level-to2: 30
need-level-to3: 40
need-level-to4: 25
need-level-to5: 30

#Settings for Database
enabled-mysql: true
host: localhost
port: 3306
username: erudo
password: password
database: emine-jobs