# Setting Language
language: ja

#Setting Level UP exp
need-exp-levelup: 100

#Settings for Database
enabled-mysql: true
host: localhost
port: 3306
username: erudo
password: password
database: emine-jobs